version: "3"
services:
  discord-helmholtz:
    restart: always
    build: .
    environment: 
      DISCORD_TOKEN: "discord_bot_token"
      DISCORD_GUILD_ID: "discord_guild_id"
      DISCORD_SOURCE_CHANNEL_ID: "discord_channel_id"
      GOOGLE_APPLICATION_CREDENTIALS: "sa-key.json"
    volumes: 
      - source: gcp-sa-key
        target: /helmholtz/sa-key.json
        uid: '0'
        gid: '0'
        mode: 600
configs:
  gcp-sa-key:
    file: ./sa-key.json
